export const TEXT_CONTENT_REQUEST = 'TEXT_CONTENT_REQUEST';
export const TEXT_CONTENT_SUCCESS = 'TEXT_CONTENT_SUCCESS';
export const TEXT_CONTENT_FAIL = 'TEXT_CONTENT_FAIL';

export const TEXT_UPDATE_REQUEST = 'TEXT_UPDATE_REQUEST';
export const TEXT_UPDATE_SUCCESS = 'TEXT_UPDATE_SUCCESS';
export const TEXT_UPDATE_FAIL = 'TEXT_UPDATE_FAIL';
export const TEXT_UPDATE_RESET = 'TEXT_UPDATE_FAIL';
